name: C/C++ CI

on:
  pull_request:
    branches: [ topic/MPI ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
           submodules: true
    - name: configure
      run: |
         sudo apt-get update
         sudo apt-get install -y --fix-missing xsdcxx libxerces-c-dev libboost-dev openmpi-bin libopenmpi-dev
         git checkout topic/MPI
         ./configure CXX=mpicxx
    - name: make
      run: make -j4
    
