name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
           submodules: true
    - name: configure
      run: |
         sudo apt-get update
         sudo apt-get install -y --fix-missing g++-9 xsdcxx libxerces-c-dev libboost-dev
         ./configure CXX=g++-9
    - name: make
      run: make -j4
    
